name: Java CI with Maven

on:
  push:
    branches:
      - '**' 
  # pull_request:
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # - name: Exit on merge commit
      #   if: env.is_merge == 'true'
      #   run: echo "This is a merge commit. Exiting."

      - name: Install Newman
        run: npm install -g newman

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          FIREBASE_CONFIG: ${{ secrets.FB_SECRET_KEY }}
          CI: true

      - name: Run Tests with Maven
        run: mvn test
        env:
          FIREBASE_CONFIG: ${{ secrets.FB_SECRET_KEY }}
          CI: true
      
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.11
        with:
          reports: target/site/jacoco/jacoco.xml
          reporttypes: HtmlInline;Cobertura;TextSummary
          sourcedirs: src/main/java/dev/coms4156/project/druginteraction
          title: JaCoCo code coverage report
        env:
          FIREBASE_CONFIG: ${{ secrets.FB_SECRET_KEY }}
          CI: true
      
      - name: JaCoCoSummary
        run: cat coveragereport/Summary.txt
        env:
          FIREBASE_CONFIG: ${{ secrets.FB_SECRET_KEY }}
          CI: true
      
      - name: Run PMD Static Analysis
        run: |
          mkdir -p coveragereport/pmd 
          mvn pmd:check > coveragereport/pmd/pmd_report.txt || true
        env:
          FIREBASE_CONFIG: ${{ secrets.FB_SECRET_KEY }}
          CI: true

      - name: Print PMD Static Analysis
        run: |
          cat coveragereport/pmd/pmd_report.txt
        env:
          FIREBASE_CONFIG: ${{ secrets.FB_SECRET_KEY }}
          CI: true

      - name: Run Checkstyle
        run: |
          mkdir -p coveragereport/checkstyle  # Create folder for Checkstyle reports
          mvn checkstyle:check > coveragereport/checkstyle/checkstyle_report.txt || true
        env:
          FIREBASE_CONFIG: ${{ secrets.FB_SECRET_KEY }}
          CI: true
      
      - name: Print Checkstyle
        run: |
          cat coveragereport/checkstyle/checkstyle_report.txt
        env:
          FIREBASE_CONFIG: ${{ secrets.FB_SECRET_KEY }}
          CI: true
      
      - name: Run Postman Tests
        run: |
          cd postman
          newman run postman_tests.json

      
