name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: List files in the workspace (for debugging)
        run: ls -la

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: List files for debugging
        run: ls -la ./firebase_config.json

      - name: Run Tests with Maven
        run: mvn test